name: 'terraform'
description: 'Install terraform and login into teraform cloud'
inputs:
  TF_TOKEN:
    description: 'Login into Terraform'
    required: true
    
 
runs:
   
   using: composite 
   steps:
   
     # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

     # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1.0.1
      with:
        cli_config_credentials_token: ${{ inputs.TF_TOKEN }}
        
    - name: Terraform Init
      shell: bash
      run: terraform init

    - name: Terraform Format
      shell: bash
      run: terraform fmt -check

    - name: Terraform Plan
      id: plan
      shell: bash
      run: terraform plan
  
           
  
